;WAP TO MULTIPLY 16-BIT NO BY 8-BIT NO.

DATA SEGMENT
    NUM1 DW 1234H
    NUM2 DB 12H
    RESULT DD ?
DATA ENDS

CODE SEGMENT
    START:
    ASSUME CS:CODE DS:DATA
    MOV AX,DATA
    MOV DS,AX
    MOV AX,NUM1 
    MOV BL,NUM2
    MOV BH,00H
    MUL BX
    MOV RESULT,AX  
    MOV RESULT+2,DX
CODE ENDS
    END START